# Generated by Django 4.2.30 on 2026-09-29 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contribution_type', models.CharField(choices=[('MONTHLY', 'Monthly Mandatory Contribution'), ('VOLUNTARY', 'Additional Voluntary Contribution (AVC)')], default='MONTHLY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contribution_year', models.PositiveIntegerField()),
                ('contribution_month', models.PositiveIntegerField(help_text='Month of contribution (1-12)')),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('transaction_reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Validation'), ('VALIDATED', 'Validated'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
