# Generated by Django 4.2.30 on 2026-09-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='members.member'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(condition=models.Q(('contribution_type', 'MONTHLY'), ('is_deleted', False)), fields=('member', 'contribution_year', 'contribution_month'), name='unique_monthly_contribution_per_member'),
        ),
    ]
