# Generated by Django 4.2.30 on 2026-09-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='transaction_reference',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
    ]
