# Generated by Django 4.2.30 on 2026-09-29 19:48

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('principal_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('annual_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('10.50'), max_digits=5)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Interest Accrual',
                'verbose_name_plural': 'Interest Accruals',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='JobExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('job_name', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Completed Successfully'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('items_processed', models.PositiveIntegerField(default=0)),
                ('details', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Job Execution Log',
                'verbose_name_plural': 'Job Execution Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('CONTRIBUTION_VALIDATED', 'Contribution Validated'), ('CONTRIBUTION_FAILED', 'Contribution Failed / Alert'), ('BENEFIT_UPDATE', 'Benefit Eligibility Updated'), ('INTEREST_CREDITED', 'Interest Credited')], max_length=40)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
