# Generated by Django 4.2.30 on 2026-09-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestaccrual',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_accruals', to='members.member'),
        ),
        migrations.AddConstraint(
            model_name='interestaccrual',
            constraint=models.UniqueConstraint(fields=('member', 'year', 'month'), name='unique_monthly_interest_per_member'),
        ),
    ]
