# Generated by Django 4.2.30 on 2026-09-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interestaccrual',
            name='unique_monthly_interest_per_member',
        ),
        migrations.AddConstraint(
            model_name='interestaccrual',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('member', 'year', 'month'), name='unique_monthly_interest_per_member'),
        ),
    ]
