# Generated by Django 4.2.30 on 2026-09-29 19:48

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('months_contributed', models.PositiveIntegerField(default=0)),
                ('total_contributions_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_eligible', models.BooleanField(db_index=True, default=False)),
                ('eligibility_type', models.CharField(choices=[('NONE', 'Not Yet Eligible'), ('MINIMUM_SERVICE', 'Minimum Contribution Period (60 Months / 5 Years)'), ('RETIREMENT', 'Retirement Age Qualified (50+ Years)'), ('SPECIAL', 'Special Exemption Approved')], default='NONE', max_length=30)),
                ('status_notes', models.TextField(blank=True, default='')),
                ('last_evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Benefit Eligibility',
                'verbose_name_plural': 'Benefit Eligibilities',
            },
        ),
    ]
