# Generated by Django 4.2.30 on 2026-09-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefiteligibility',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_eligibility', to='members.member'),
        ),
    ]
